// Curates Pexels media for "rise" — a youth & community charity site.
// Run: node fetch-media.mjs   (or PEXELS_KEY=... node fetch-media.mjs)
const KEY = process.env.PEXELS_KEY || "IPVJsE6aClRZFz8KpSqWAVL82P2OOJZtZ77ufubkLBz2lOLd4YxF0Lls";
import { writeFileSync } from "node:fs";

const headers = { Authorization: KEY };

async function photos(query, { per = 1, orientation = "landscape", page = 1 } = {}) {
  const url = `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=${per}&orientation=${orientation}&page=${page}`;
  const r = await fetch(url, { headers });
  const d = await r.json();
  return (d.photos || []).map((p) => ({
    img: p.src.large2x || p.src.large,
    imgPortrait: p.src.portrait,
    tiny: p.src.tiny,
    alt: p.alt || query,
    credit: p.photographer,
    creditUrl: p.photographer_url,
  }));
}

async function video(query, { orientation = "landscape", page = 1 } = {}) {
  const url = `https://api.pexels.com/videos/search?query=${encodeURIComponent(query)}&per_page=1&orientation=${orientation}&page=${page}`;
  const r = await fetch(url, { headers });
  const d = await r.json();
  const v = (d.videos || [])[0];
  if (!v) return null;
  const files = v.video_files.filter((f) => f.width && f.height).sort((a, b) => b.width - a.width);
  const hd = files.find((f) => f.width <= 1920 && f.width >= 1280) || files[0];
  return { mp4: hd.link, poster: v.image, credit: v.user?.name, creditUrl: v.user?.url };
}

const media = {};

console.log("fetching hero...");
media.hero = await video("diverse young people volunteering community together");
media.heroPoster = (await photos("diverse group young people smiling community outdoors"))[0];

console.log("fetching programme pillars...");
media.mentor = {
  photo: (await photos("mentor talking with young person guidance support"))[0],
  video: await video("mentor mentoring young person conversation support"),
};
media.learn = {
  photo: (await photos("diverse students learning workshop classroom teenagers"))[0],
  video: await video("young people studying workshop classroom learning"),
};
media.belong = {
  photo: (await photos("diverse teenagers friends community youth center together"))[0],
  video: await video("young people laughing together community group friends"),
};

console.log("fetching testimonial portraits...");
const portraitQueries = [
  "portrait young man hopeful smiling diverse",
  "portrait young woman student confident smiling",
  "portrait teenager smiling natural light",
  "portrait young volunteer smiling friendly",
  "portrait young person joyful diverse",
];
media.testimonials = [];
for (const q of portraitQueries) {
  const p = (await photos(q, { orientation: "portrait" }))[0];
  if (p) media.testimonials.push(p);
}

console.log("fetching scatter images...");
const scatterQueries = [
  "young people volunteering community project",
  "students graduation celebrating success diverse",
  "youth sport team together happy",
  "volunteers helping community outdoors",
  "young people art music class creative",
  "teenagers studying together library",
  "diverse group friends outdoors laughing youth",
];
media.scatter = [];
for (const q of scatterQueries) {
  const p = (await photos(q))[0];
  if (p) media.scatter.push(p);
}

console.log("fetching ways-to-help cards...");
media.cards = {
  volunteer: (await photos("mentor volunteer with young person smiling support"))[0],
  give: (await photos("young people graduating celebrating bright future diverse"))[0],
};

console.log("fetching community + giving backgrounds...");
media.community = (await photos("diverse community group young people together hopeful"))[0];
media.ctaSubs = await video("diverse people helping community hopeful together");

const out = "// AUTO-GENERATED by fetch-media.mjs from the Pexels API\nwindow.HAPPLY_MEDIA = " +
  JSON.stringify(media, null, 2) + ";\n";
writeFileSync(new URL("./assets/js/media.js", import.meta.url), out);
console.log("\nWrote assets/js/media.js");
console.log("hero video:", media.hero?.mp4 ? "ok" : "MISSING");
console.log("pillars:", ["mentor", "learn", "belong"].map((k) => `${k}:${media[k].video?.mp4 ? "vid" : "img"}`).join(" "));
console.log("testimonials:", media.testimonials.length, "scatter:", media.scatter.length);
